### ISSUE TITLE
Error in Filepath

### ISSUE THREAD

**Issue by dawoat** [ennerperez/msbuild-obfuscar#3]
Your tool uses Hardcoded Filepath in Solution:
Severity	Code	Description	Project	File	Line	Suppression State

Error		
Unable to locate 'C:\Users\Wolfgang\.nuget\packages\Obfuscar.2.2.26\tools\Obfuscar.Console.exe'	

The Correct FilePath after insatlling Obfuscar via NuGet is:
C:\Users\Wolfgang\.nuget\packages\Obfuscar\2.2.26\tools\Obfuscar.Console.exe

**Comment by egarim** [comment]
@dawoat the path for the nuget is wrong I fixed it in a clone of this repo

https://github.com/egarim/msbuild-obfuscar

**Comment by ennerperez** [comment]
Using https://www.nuget.org/packages/Obfuscar/
Right now going to move to 2.2.28

**Comment by sigmarsson** [comment]
The build error keeps persisting across several package versions; 
`Obfuscar.2.2.26`
Could any1 replace the first dot with a backslash ?
Is it expected to work with netcoreapp3.1 ?
